### PR TITLE
Fix http server tck tests

### LINKED ISSUE #788: Investigate and fix TCK server exclusions for Micronaut 4.0.0
In https://github.com/micronaut-projects/micronaut-gcp/pull/787 we have added the Server TCK to the project and had to exclude quite a few TCK tests as they currently appear to be broken.

These should be investigated and fixed prior to 4.0.0 GA

- [ ] `io.micronaut.http.server.tck.tests.BodyTest` -- Bad Request 400 errors
- [ ] `io.micronaut.http.server.tck.tests.ConsumesTest` -- Bad Request 400 errors
- [ ] `io.micronaut.http.server.tck.tests.CookiesTest` -- Cookies are not handled, I suspect as it's not implemented in the NettyClientHttpRequest
- [ ] `io.micronaut.http.server.tck.tests.ErrorHandlerTest` -- testCustomGlobalExceptionHandlersForPOSTWithBody fails; cannot get ErrorHandlerTest$RequestObject no String-argument constructor/factory method to deserialize from String value ('{\"numberField\":101}')
- [ ] `io.micronaut.http.server.tck.tests.FluxTest` -- Body is returned as '{"scanAvailable":true,"prefetch":-1}'
- [ ] `io.micronaut.http.server.tck.tests.MiscTest` -- Bad Request 400 errors
- [ ] `io.micronaut.http.server.tck.tests.OctetTest` -- Received body contains 512 bytes, expected 256 (encoding type?)
- [ ] `io.micronaut.http.server.tck.tests.filter.ClientRequestFilterTest` -- Multiple errors, mostly 404s
- [ ] `io.micronaut.http.server.tck.tests.filter.ClientResponseFilterTest` -- Multiple errors
- [ ] `io.micronaut.http.server.tck.tests.filter.RequestFilterExceptionHandlerTest` -- Request is immutable
- [ ] `io.micronaut.http.server.tck.tests.filter.RequestFilterTest` -- Request is immutable
- [ ] `io.micronaut.http.server.tck.tests.filter.ResponseFilterTest` -- Request is immutable

### PR DESCRIPTION
**Pull request by wetted**
fixes #788

### CODE REVIEW

**Comment by timyates** [comment]
Looking good...

I pushed a fix for the Cookies test (and the Headers test) which was caused by case sensitivity for the header names

I also pushed a change (grabbed from AWS) to fix the Health test

The Controller constraint test will need [something like this](https://github.com/micronaut-projects/micronaut-servlet/pull/477/files#diff-b39f9b630b9c988a8aa1af4acb7486253349849955cc217a732a885c4266df78) -- which I think is in this [PR for AWS](https://github.com/micronaut-projects/micronaut-aws/pull/1760/commits/1ac27f6401f3d5c03334d61817119595cdb305bd)

**Comment by timyates** [comment]
FYI: We have the double checked locking in [AWS as well](https://github.com/micronaut-projects/micronaut-aws/blob/52d5cf78632d8a7b6f7d7ede83bb39451f280de0/function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/ApiGatewayServletRequest.java#L155), but it's different and doesn't flag as a critical error

**Comment by timyates** [comment]
I'm going to test on actual GCP

**Review by sdelamo — APPROVED** [review]

**Comment by timyates** [comment]
Tested this on GCP, and it seems to worked for me 👍

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
