### PR TITLE
Fix default content type and Acknowledgement binding

### PR DESCRIPTION
**Pull request by ajtuss**

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks, can you sign the CLA?

**Comment by graemerocher** [comment]
@viniciusccarvalho Thoughts on this?

**Comment by ajtuss** [comment]
@graemerocher Thanks, I didn't notice that. Signed.

**Comment by viniciusccarvalho** [comment]
Hi @ajtuss thanks for the contribution. I need to look into it all, still early morning for me here :)

One point I want to raise on the `content-type`, the ack was a good catch ;)

Seems that this commit will change the default behavior of "fail if no content is present", at least that was a design choice inspired by my experience as a Spring Cloud Stream engineer days. We had on version 1.x of SCSt a very opinionated way to do ser/des and that caused all types of issues. It took us an entire afternoon in a summit with all developers to agree on a much simplified model, something that I used here:

Basically, we force contentType for output, because consumers outside of your application can easily ignore them, but as we force all messages to have a contentType we guarantee that our consumers can rely on it to process incoming messages. 

SCSt was a bit different as it tried to "guess" the content type and not really choose a fixed type, but the rationale is still that if a producer does not tell you what is the payload you should not try to guess, chances are they may be json, but we can not be sure. This is why I believe we should not have a default type to receive, if this is not working today that was a mistake on my end.

@graemerocher open to hear opinions on that, in the end there's no right/wrong it is a default behavior the framework should take and we just need to make sure we document that.

**Comment by viniciusccarvalho** [comment]
@graemerocher this LGTM fixes issues and having more tests is always a great thing. Reminds me to make a contribution with one extra test for content type

**Pull request merged**
