### PR TITLE
Fix default project id initialization (#479)

### PR DESCRIPTION
**Pull request by fromlabs**

### CODE REVIEW

**Review by sdelamo — COMMENTED** [review]
Can you provide a link to documentation about `_IS_UNDEFINED`?

**Comment by fromlabs** [comment]
As I said in #479, debugging my application, I've found a code misalignment in `StackdriverJsonLayout.start()` where the condition wasn't complete as in `StackdriverJsonLayout.addTraceId()`.

Briefly my fix was just copying a condition already found in your code, I didn't dig into logback details.

I haven't found documentation on `_IS_UNDEFINED`, but looking in logback-core code, I found a reference in `CoreConstants` and `NodeToStringTransformer`.
I suppose that logback parses `logback-json-appender.xml` and when it comes to `<projectId>${projectId}</projectId>`, expression `${projectId}` evaluates to `projectId_IS_UNDEFINED` when not defined (and not to`null`) (_logback-core-1.2.10-sources.jar!/ch/qos/logback/core/subst/NodeToStringTransformer.java:103_).

Hope it helps you.

**Comment by pkarolis** [comment]
Any update on this PR? Is there anything pending to get this merged? 

I am looking to get a resolution for issue #479. 

Thank you

**Comment by cssil** [comment]
Hi,

My team is facing same issue as described #479. Without this pull request it cannot be addressed. 

Can somebody please provide an update and why this PR is not being merged?

Thanks, Silvestras

**Comment by graemerocher** [comment]
PRs without tests are merged with caution but in this case enough people have hit the same problem so ok

**Pull request merged**
